import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { ConnectWallet, Web3Button, ThirdwebNftMedia, useAddress, useContract } from "@thirdweb-dev/react";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

    // Connect to your NFT contract
    // const { contract } = useContract("{{contract_address}}");
    // Load the NFT metadata from the contract using a hook
    // const { data: nft, isLoading, error } = useNFT(contract, "0");

    // Render the NFT onto the UI
    // if (isLoading) return <div>Loading...</div>;
    // if (error || !nft) return <div>NFT not found</div>;

    const address = useAddress();

    function WalletAddress({ address }) {
      if (!address) {
        return <div>No wallet connected</div>;
      }
    
      return <div>My wallet address is {address}</div>;
    }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

      {/* <Web3Button
      contractAddress="{{contract_address}}"
      action={async (contract) => contract.call("myFunctionName")}
    >
      Call myFunctionName from the connected wallet
      </Web3Button> */}

      <ConnectWallet
      theme="dark"
      btnTitle="Connect Wallet"
    />

    {/* <Web3Button
      contractAddress="0x..."
      action={(contract) => console.log(contract)} // Logic to execute when clicked
      onSubmit={() => console.log("Transaction submitted")} //Callback function to be run after the user has confirmed the transaction.
      onSuccess={(result) => alert("Success!")} //Callback function to be run when the contract method call is successful.
      onError={(error) => alert("Something went wrong!")} //Callback function to be run when the contract method call fails.
    >
      Create Social Profile
    </Web3Button> */}

    {/* <ThirdwebNftMedia 
    metadata={nft.metadata} 
    width={500}
    height={500}

    /> */}

    <WalletAddress address={address} />

      </main>
    </>
  )
}
